### ISSUE TITLE
Access to Other `chrome://` URLs

### ISSUE THREAD

**Issue by pahosler** [Darksmurf/history.awesomeify#2]
I take back what I said... I got it working! Currently it opens new tabs, trying to figure out how to make it open under current tab.

**Comment by Darksmurf** [comment]
Wow, thanks! What if when the user clicked it, for now, we have it open in a new tab, and then close the current tab.

**Comment by pahosler** [comment]
I tried to make it pass the url to the function so there wouldn't be a function for each link but for some reason that put it in an infinite loop. so for now there has to be a click request for each link and a function for each click request. I'm not sure if it's a google bug or lack of knowledge for how the api is actually supposed to work :open_mouth:

**Comment by Darksmurf** [comment]
Yeah, it should be fine. I'll look at it later and see if I can do
anything. Right now I'm just tidying things up with CSS.
